export const FETCH_TWEETS_SUCCESS = 'FETCH_TWEETS_SUCCESS'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS'
